# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PickUpLocations' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PickUpLocations

  target 'PickUpLocationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PickUpLocationsUITests' do
    # Pods for testing
  end
  pod 'Alamofire', '~> 4.8.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'KRProgressHUD'
end
